services:
  app:
    image: ghcr.io/reinayla-amaria/backend-lapanginaja:latest
    container_name: lapanginaja
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db_lapangan
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpasswordharusnyaunik
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:

